./check-todo.py : [12]
./docs/intro.txt : [40]
./docs/_build/html/_sources/intro.txt : [40]
./pinax/apps/account/forms.py : [102, 111, 362]
./pinax/apps/account/models.py : [72]
./pinax/apps/account/views.py : [86, 267]
./pinax/apps/autocomplete_app/views.py : [4, 14]
./pinax/apps/basic_profiles/templates/profile_item.html : [6]
./pinax/apps/bbauth/views.py : [6, 23]
./pinax/apps/blog/views.py : [84, 88, 117]
./pinax/apps/groups/helpers.py : [51]
./pinax/apps/photos/views.py : [148]
./pinax/apps/profiles/views.py : [77, 88, 98, 108]
./pinax/apps/profiles/templates/profile_item.html : [7]
./pinax/apps/projects/forms.py : [8, 31]
./pinax/apps/projects/models.py : [24]
./pinax/apps/projects/views.py : [46, 83, 138]
./pinax/apps/projects/templatetags/projects_tags.py : [10]
./pinax/apps/tasks/forms.py : [81]
./pinax/apps/tasks/management.py : [8]
./pinax/apps/tasks/models.py : [44, 169, 187]
./pinax/apps/tasks/views.py : [157, 365, 366, 471, 476, 485, 492, 495, 498, 500]
./pinax/apps/tasks/workflow.py : [149]
./pinax/apps/tasks/templatetags/tasks_tags.py : [97]
./pinax/apps/tasks/tests/test_models.py : [26]
./pinax/apps/topics/models.py : [59, 60]
./pinax/apps/topics/views.py : [10, 58]
./pinax/apps/tribes/forms.py : [6, 29]
./pinax/apps/tribes/views.py : [45, 82, 130, 135]
./pinax/apps/tribes/templatetags/tribes_tags.py : [11]
./pinax/fixtures/generate/gen_account.py : [18]
./pinax/media/default/pinax/css/comments.css : [1]
./pinax/media/default/pinax/css/paste.css : [1]
./pinax/projects/code_project/apps/tag_app/views.py : [30]
./pinax/projects/intranet_project/apps/tag_app/views.py : [31]
./pinax/projects/private_beta_project/urls.py : [15]
./pinax/projects/sample_group_project/apps/basic_groups/forms.py : [6, 29]
./pinax/projects/sample_group_project/apps/basic_groups/views.py : [31, 54, 89]
./pinax/projects/sample_group_project/apps/basic_groups/templates/basic_groups/group_item.html : [9]
./pinax/projects/sample_group_project/apps/basic_groups/templatetags/basic_group_tags.py : [12]
./pinax/projects/social_project/urls.py : [72]
./pinax/projects/social_project/apps/friends_app/forms.py : [7]
./pinax/projects/social_project/apps/friends_app/views.py : [14, 33]
./pinax/projects/social_project/apps/tag_app/views.py : [25]
./pinax/templates/default/account/login.html : [39]
./pinax/templates/default/account/signup.html : [31]
./pinax/templates/default/blog/new.html : [10]
./pinax/templates/default/bookmarks/bookmarks.html : [22]
./pinax/templates/default/bookmarks/friends_bookmarks.html : [14, 20, 111]
./pinax/templates/default/messages/compose.html : [34]
./pinax/templates/default/microblogging/followers.html : [17, 19]
./pinax/templates/default/microblogging/following.html : [16, 18]
./pinax/templates/default/microblogging/personal.html : [16]
./pinax/templates/default/microblogging/public.html : [9]
./pinax/templates/default/notification/notices.html : [23]
./pinax/templates/default/profiles/profile.html : [55, 66]
./pinax/templates/default/projects/project_item.html : [11]
./pinax/templates/default/swaps/offers.html : [78]
./pinax/templates/default/tasks/focus.html : [3, 19]
./pinax/templates/default/tasks/task_list.html : [15]
./pinax/templates/default/tasks/task_list_detail.html : [13]
./pinax/templates/default/tribes/tribe_item.html : [11]
./pinax/templates/default/wiki/view.html : [48]
./scripts/_installer.py : [211]
./scripts/pinax-boot.py : [553, 635, 734, 755, 758, 809, 1206, 1578]
